// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...x
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo7qTHh_wKD1bYIQu_IVV5yvE3Mw9jQrk',
    appId: '1:522125772075:web:7dddd6409ca7ae2dbbf16e',
    messagingSenderId: '522125772075',
    projectId: 'my-store-fb27a',
    authDomain: 'my-store-fb27a.firebaseapp.com',
    databaseURL: 'https://my-store-fb27a-default-rtdb.firebaseio.com',
    storageBucket: 'my-store-fb27a.firebasestorage.app',
    measurementId: 'G-T5V4PV22PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt-jQH1ieSJcicKNFMOt_7zrXpTW2BQ9Y',
    appId: '1:522125772075:android:2bfe336019556998bbf16e',
    messagingSenderId: '522125772075',
    projectId: 'my-store-fb27a',
    databaseURL: 'https://my-store-fb27a-default-rtdb.firebaseio.com',
    storageBucket: 'my-store-fb27a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo7qTHh_wKD1bYIQu_IVV5yvE3Mw9jQrk',
    appId: '1:522125772075:web:6a596274f04656acbbf16e',
    messagingSenderId: '522125772075',
    projectId: 'my-store-fb27a',
    authDomain: 'my-store-fb27a.firebaseapp.com',
    databaseURL: 'https://my-store-fb27a-default-rtdb.firebaseio.com',
    storageBucket: 'my-store-fb27a.firebasestorage.app',
    measurementId: 'G-WG6DBGJN8H',
  );

}